# Generated by Django 2.2.6 on 2019-11-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='cake_Name',
            new_name='cake_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commnent_id',
            new_name='comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='descr',
            field=models.TextField(blank=True),
        ),
    ]
