# Generated by Django 2.2.6 on 2019-11-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_auto_20191104_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
