# Generated by Django 2.2.6 on 2019-11-08 01:29

import cakes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_auto_20191104_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cake_picture',
            field=models.ImageField(blank=True, null=True, upload_to=cakes.models.getImagePath),
        ),
    ]
